services:
  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - /volume/loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki-data:/loki
    restart: unless-stopped
    
  alloy:
    image: grafana/alloy:latest  
    container_name: alloy
    depends_on:
      - loki
    volumes:
      - /volume/alloy:/etc/alloy
      - /var/log:/var/log:ro  # linux log
    restart: unless-stopped  
    command:
      - run
      - /etc/alloy/config.alloy

  grafana:
    image: grafana/grafana:latest
    ports:
      - "9010:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=1qaz2wsx3edc
      - GRAFANA_API_TOKEN_TYPE=service_account_token
      - GF_FEATURE_TOGGLES_ENABLE=externalServiceAccounts
    volumes:
      - /volume/grafana:/var/lib/grafana
    user: root
    deploy:
      resources:
        limits:
          memory: 500m
          cpus: "0.5"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-remote-write-receiver"   
    ports:
      - "9090:9090"
    volumes:
      - /volume/prometheus:/etc/prometheus
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - /volume/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9012:9093"
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    environment:
      - TZ=Asia/Taipei

  node_exporter:
    image: prom/node-exporter:v1.9.1
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  
  
  # cadvisor:
  #   image: google/cadvisor:latest
  #   container_name: cadvisor
  #   privileged: true
  #   restart: unless-stopped
  #   ports:
  #     - "9080:8080"
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:ro
  #     - /sys:/sys:ro
  #     - /var/lib/docker:/var/lib/docker:ro
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro  # 需要將v2改成v1 參考https://blog.trfox.top/posts/devops/ubuntu24-cadvisor-cpu-mount-point-error-fix
  #     - /dev/disk/:/dev/disk:ro
    



volumes:
    loki-data: {}